:kscriptLink: https://github.com/holgerbrandl/kscript[kscript]

= Gradle Profiler Wrapper

A wrapper for the https://github.com/gradle/gradle-profiler[gradle profiler], 
it allows you to include just the executable binary of this
script to run an up to date version of the gradle profiler.

== Usage

To use the wrapper, simply download the binary from github and run it like you 
would run the gradle-profiler. 

Example: 
`gradle-profilerw --profiler buildscan --build-dir /path/to/project assemble`. 

If you need to update the gradle-profiler that has been cached run 
`gradle-profilerw --force-update`

== Development 

This script uses {kscriptLink}. It's 
recommened to install {kscriptLink} from https://sdkman.io/[sdkman].

To create the binary file for deployment simply run

`kscript --package gradle-profilerw.kts`

This will create a stand alone binary that can be run on unix systems.

== Future Goals

. Tests
. Better error handling
. Windows support

== License

```
Copyright 2019 Andrew Reitz

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
```
